import sys
import locale
import Forms.formRegisterPayments_support as paySup

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    
class RegisterPayments:
    def Show(Container=None,Cart=None):
        locale.setlocale( locale.LC_ALL, '' )
        for child in Container.winfo_children():
            child.destroy()

        paySup.formPayments=Container
        paySup.classCart=Cart

        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        Container.configure(background="#d9d9d9")
        Container.configure(highlightbackground="#d9d9d9")
        Container.configure(highlightcolor="black")

        Container.Label1 = tk.Label(Container)
        Container.Label1.place(relx=0.096, rely=0.018, height=21, width=127)
        Container.Label1.configure(activebackground="#f9f9f9")
        Container.Label1.configure(activeforeground="black")
        Container.Label1.configure(anchor='e')
        Container.Label1.configure(background="#d9d9d9")
        Container.Label1.configure(disabledforeground="#a3a3a3")
        Container.Label1.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.Label1.configure(foreground="#000000")
        Container.Label1.configure(highlightbackground="#d9d9d9")
        Container.Label1.configure(highlightcolor="black")
        Container.Label1.configure(text='''Amount Due:''')

        Container.lblAmountDue = tk.Label(Container)
        Container.lblAmountDue.place(relx=0.273, rely=0.018, height=21, width=75)
        Container.lblAmountDue.configure(activebackground="#f9f9f9")
        Container.lblAmountDue.configure(activeforeground="black")
        Container.lblAmountDue.configure(anchor='e')
        Container.lblAmountDue.configure(background="#d9d9d9")
        Container.lblAmountDue.configure(disabledforeground="#a3a3a3")
        Container.lblAmountDue.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.lblAmountDue.configure(foreground="#000000")
        Container.lblAmountDue.configure(highlightbackground="#d9d9d9")
        Container.lblAmountDue.configure(highlightcolor="black")
        Container.lblAmountDue.configure(text=locale.currency(Cart.GetCartTotal()))

        Container.Label3 = tk.Label(Container)
        Container.Label3.place(relx=0.068, rely=0.07, height=21, width=149)
        Container.Label3.configure(activebackground="#f9f9f9")
        Container.Label3.configure(activeforeground="black")
        Container.Label3.configure(anchor='e')
        Container.Label3.configure(background="#d9d9d9")
        Container.Label3.configure(disabledforeground="#a3a3a3")
        Container.Label3.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.Label3.configure(foreground="#000000")
        Container.Label3.configure(highlightbackground="#d9d9d9")
        Container.Label3.configure(highlightcolor="black")
        Container.Label3.configure(text='''Amount Paid:''')

        Container.lblAmountPaid = tk.Label(Container)
        Container.lblAmountPaid.place(relx=0.273, rely=0.07, height=21, width=75)
        Container.lblAmountPaid.configure(activebackground="#f9f9f9")
        Container.lblAmountPaid.configure(activeforeground="black")
        Container.lblAmountPaid.configure(anchor='e')
        Container.lblAmountPaid.configure(background="#d9d9d9")
        Container.lblAmountPaid.configure(disabledforeground="#a3a3a3")
        Container.lblAmountPaid.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.lblAmountPaid.configure(foreground="#000000")
        Container.lblAmountPaid.configure(highlightbackground="#d9d9d9")
        Container.lblAmountPaid.configure(highlightcolor="black")
        Container.lblAmountPaid.configure(text=locale.currency(Cart.GetCartPaymentTotal()))

        Container.Label5 = tk.Label(Container)
        Container.Label5.place(relx=0.027, rely=0.123, height=21, width=177)
        Container.Label5.configure(activebackground="#f9f9f9")
        Container.Label5.configure(activeforeground="black")
        Container.Label5.configure(anchor='e')
        Container.Label5.configure(background="#d9d9d9")
        Container.Label5.configure(disabledforeground="#a3a3a3")
        Container.Label5.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.Label5.configure(foreground="#000000")
        Container.Label5.configure(highlightbackground="#d9d9d9")
        Container.Label5.configure(highlightcolor="black")
        Container.Label5.configure(text='''Amount Remaining:''')

        Container.lblRemaining = tk.Label(Container)
        Container.lblRemaining.place(relx=0.273, rely=0.123, height=21, width=75)
        Container.lblRemaining.configure(activebackground="#f9f9f9")
        Container.lblRemaining.configure(activeforeground="black")
        Container.lblRemaining.configure(anchor='e')
        Container.lblRemaining.configure(background="#d9d9d9")
        Container.lblRemaining.configure(disabledforeground="#a3a3a3")
        Container.lblRemaining.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.lblRemaining.configure(foreground="#000000")
        Container.lblRemaining.configure(highlightbackground="#d9d9d9")
        Container.lblRemaining.configure(highlightcolor="black")
        Container.lblRemaining.configure(text=locale.currency(Cart.GetCartTotal()-Cart.GetCartPaymentTotal()))

        Container.TSeparator1 = ttk.Separator(Container)
        Container.TSeparator1.place(relx=0.027, rely=0.175, relwidth=0.504)

        Container.TSeparator3 = ttk.Separator(Container)
        Container.TSeparator3.place(relx=0.027, rely=0.474, relwidth=0.504)

        Container.txtAmount = tk.Entry(Container)
        Container.txtAmount.place(relx=0.273, rely=0.184,height=30, relwidth=0.101)
        Container.txtAmount.configure(background="white")
        Container.txtAmount.configure(disabledforeground="#a3a3a3")
        Container.txtAmount.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.txtAmount.configure(foreground="#000000")
        Container.txtAmount.configure(highlightbackground="#d9d9d9")
        Container.txtAmount.configure(highlightcolor="black")
        Container.txtAmount.configure(insertbackground="black")
        Container.txtAmount.configure(selectbackground="#c4c4c4")
        Container.txtAmount.configure(selectforeground="black")
        Container.txtAmount.delete(0,tk.END)
        Container.txtAmount.insert(0,locale.currency(Cart.GetCartTotal()-Cart.GetCartPaymentTotal()))


        Container.Label7 = tk.Label(Container)
        Container.Label7.place(relx=0.164, rely=0.193, height=21, width=75)
        Container.Label7.configure(activebackground="#f9f9f9")
        Container.Label7.configure(activeforeground="black")
        Container.Label7.configure(anchor='e')
        Container.Label7.configure(background="#d9d9d9")
        Container.Label7.configure(disabledforeground="#a3a3a3")
        Container.Label7.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.Label7.configure(foreground="#000000")
        Container.Label7.configure(highlightbackground="#d9d9d9")
        Container.Label7.configure(highlightcolor="black")
        Container.Label7.configure(text='''Amount:''')

        Container.btnDollarBill1 = tk.Button(Container)
        Container.btnDollarBill1.place(relx=0.014, rely=0.246, height=44, width=47)
        Container.btnDollarBill1.configure(activebackground="#ececec")
        Container.btnDollarBill1.configure(activeforeground="#000000")
        Container.btnDollarBill1.configure(background="#d9d9d9")
        Container.btnDollarBill1.configure(disabledforeground="#a3a3a3")
        Container.btnDollarBill1.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnDollarBill1.configure(foreground="#000000")
        Container.btnDollarBill1.configure(highlightbackground="#d9d9d9")
        Container.btnDollarBill1.configure(highlightcolor="black")
        Container.btnDollarBill1.configure(pady="0")
        Container.btnDollarBill1.configure(text='''$1''')

        Container.Label9 = tk.Label(Container)
        Container.Label9.place(relx=0.014, rely=0.333, height=41, width=370)
        Container.Label9.configure(activebackground="#f9f9f9")
        Container.Label9.configure(activeforeground="black")
        Container.Label9.configure(anchor='w')
        Container.Label9.configure(background="#d9d9d9")
        Container.Label9.configure(disabledforeground="#a3a3a3")
        Container.Label9.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.Label9.configure(foreground="#000000")
        Container.Label9.configure(highlightbackground="#d9d9d9")
        Container.Label9.configure(highlightcolor="black")
        Container.Label9.configure(text='''Enter the payment amount and click "Add"''')

        Container.btnValue1 = tk.Button(Container)
        Container.btnValue1.place(relx=0.587, rely=0.035, height=67, width=67)
        Container.btnValue1.configure(activebackground="#ececec")
        Container.btnValue1.configure(activeforeground="#000000")
        Container.btnValue1.configure(background="#d9d9d9")
        Container.btnValue1.configure(disabledforeground="#a3a3a3")
        Container.btnValue1.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue1.configure(foreground="#000000")
        Container.btnValue1.configure(highlightbackground="#d9d9d9")
        Container.btnValue1.configure(highlightcolor="black")
        Container.btnValue1.configure(pady="0")
        Container.btnValue1.configure(text='''1''')

        Container.Label10 = tk.Label(Container)
        Container.Label10.place(relx=0.014, rely=0.719, height=21, width=95)
        Container.Label10.configure(activebackground="#f9f9f9")
        Container.Label10.configure(activeforeground="black")
        Container.Label10.configure(background="#d9d9d9")
        Container.Label10.configure(disabledforeground="#a3a3a3")
        Container.Label10.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.Label10.configure(foreground="#000000")
        Container.Label10.configure(highlightbackground="#d9d9d9")
        Container.Label10.configure(highlightcolor="black")
        Container.Label10.configure(text='''Payments:''')

        Container.btnDollarBill5 = tk.Button(Container)
        Container.btnDollarBill5.place(relx=0.082, rely=0.246, height=44, width=47)
        Container.btnDollarBill5.configure(activebackground="#ececec")
        Container.btnDollarBill5.configure(activeforeground="#000000")
        Container.btnDollarBill5.configure(background="#d9d9d9")
        Container.btnDollarBill5.configure(disabledforeground="#a3a3a3")
        Container.btnDollarBill5.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnDollarBill5.configure(foreground="#000000")
        Container.btnDollarBill5.configure(highlightbackground="#d9d9d9")
        Container.btnDollarBill5.configure(highlightcolor="black")
        Container.btnDollarBill5.configure(pady="0")
        Container.btnDollarBill5.configure(text='''$5''')

        Container.btnDollarBill10 = tk.Button(Container)
        Container.btnDollarBill10.place(relx=0.15, rely=0.246, height=44, width=47)
        Container.btnDollarBill10.configure(activebackground="#ececec")
        Container.btnDollarBill10.configure(activeforeground="#000000")
        Container.btnDollarBill10.configure(background="#d9d9d9")
        Container.btnDollarBill10.configure(disabledforeground="#a3a3a3")
        Container.btnDollarBill10.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnDollarBill10.configure(foreground="#000000")
        Container.btnDollarBill10.configure(highlightbackground="#d9d9d9")
        Container.btnDollarBill10.configure(highlightcolor="black")
        Container.btnDollarBill10.configure(pady="0")
        Container.btnDollarBill10.configure(text='''$10''')

        Container.btnDollarBill20 = tk.Button(Container)
        Container.btnDollarBill20.place(relx=0.219, rely=0.246, height=44, width=47)
        Container.btnDollarBill20.configure(activebackground="#ececec")
        Container.btnDollarBill20.configure(activeforeground="#000000")
        Container.btnDollarBill20.configure(background="#d9d9d9")
        Container.btnDollarBill20.configure(disabledforeground="#a3a3a3")
        Container.btnDollarBill20.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnDollarBill20.configure(foreground="#000000")
        Container.btnDollarBill20.configure(highlightbackground="#d9d9d9")
        Container.btnDollarBill20.configure(highlightcolor="black")
        Container.btnDollarBill20.configure(pady="0")
        Container.btnDollarBill20.configure(text='''$20''')

        Container.btnExactAmount = tk.Button(Container)
        Container.btnExactAmount.place(relx=0.301, rely=0.246, height=44, width=57)
        Container.btnExactAmount.configure(activebackground="#ececec")
        Container.btnExactAmount.configure(activeforeground="#000000")
        Container.btnExactAmount.configure(background="#d9d9d9")
        Container.btnExactAmount.configure(disabledforeground="#a3a3a3")
        Container.btnExactAmount.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnExactAmount.configure(foreground="#000000")
        Container.btnExactAmount.configure(highlightbackground="#d9d9d9")
        Container.btnExactAmount.configure(highlightcolor="black")
        Container.btnExactAmount.configure(pady="0")
        Container.btnExactAmount.configure(text='''Exact''')
        Container.btnExactAmount.configure(command=lambda: paySup.btnExactHandler())
        
        Container.btnAddPayment = tk.Button(Container)
        Container.btnAddPayment.place(relx=0.41, rely=0.246, height=44, width=57)
        Container.btnAddPayment.configure(activebackground="#ececec")
        Container.btnAddPayment.configure(activeforeground="#000000")
        Container.btnAddPayment.configure(background="#d9d9d9")
        Container.btnAddPayment.configure(disabledforeground="#a3a3a3")
        Container.btnAddPayment.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnAddPayment.configure(foreground="#000000")
        Container.btnAddPayment.configure(highlightbackground="#d9d9d9")
        Container.btnAddPayment.configure(highlightcolor="black")
        Container.btnAddPayment.configure(pady="0")
        Container.btnAddPayment.configure(text='''Add''')
        Container.btnAddPayment.configure(command=lambda: paySup.btnAddPaymentHandler())

        Container.btnCancel = tk.Button(Container)
        Container.btnCancel.place(relx=0.874, rely=0.895, height=44, width=67)
        Container.btnCancel.configure(activebackground="#ececec")
        Container.btnCancel.configure(activeforeground="#000000")
        Container.btnCancel.configure(background="#d9d9d9")
        Container.btnCancel.configure(disabledforeground="#a3a3a3")
        Container.btnCancel.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnCancel.configure(foreground="#000000")
        Container.btnCancel.configure(highlightbackground="#d9d9d9")
        Container.btnCancel.configure(highlightcolor="black")
        Container.btnCancel.configure(pady="0")
        Container.btnCancel.configure(text='''Cancel''')
        Container.btnCancel.configure(wraplength="60")

        Container.btnDone = tk.Button(Container)
        Container.btnDone.place(relx=0.71, rely=0.895, height=44, width=67)
        Container.btnDone.configure(activebackground="#ececec")
        Container.btnDone.configure(activeforeground="#000000")
        Container.btnDone.configure(background="#d9d9d9")
        Container.btnDone.configure(disabledforeground="#a3a3a3")
        Container.btnDone.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnDone.configure(foreground="#000000")
        Container.btnDone.configure(highlightbackground="#d9d9d9")
        Container.btnDone.configure(highlightcolor="black")
        Container.btnDone.configure(pady="0")
        Container.btnDone.configure(text='''Done''')

        Container.btnPrint = tk.Button(Container)
        Container.btnPrint.place(relx=0.546, rely=0.895, height=44, width=67)
        Container.btnPrint.configure(activebackground="#ececec")
        Container.btnPrint.configure(activeforeground="#000000")
        Container.btnPrint.configure(background="#d9d9d9")
        Container.btnPrint.configure(disabledforeground="#a3a3a3")
        Container.btnPrint.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnPrint.configure(foreground="#000000")
        Container.btnPrint.configure(highlightbackground="#d9d9d9")
        Container.btnPrint.configure(highlightcolor="black")
        Container.btnPrint.configure(pady="0")
        Container.btnPrint.configure(text='''Print''')

        #Container.Label9_11 = tk.Label(Container)
        #Container.Label9_11.place(relx=0.014, rely=0.386, height=41, width=380)
        #Container.Label9_11.configure(activebackground="#f9f9f9")
        #Container.Label9_11.configure(activeforeground="black")
        #Container.Label9_11.configure(background="#d9d9d9")
        #Container.Label9_11.configure(disabledforeground="#a3a3a3")
        #Container.Label9_11.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        #Container.Label9_11.configure(foreground="#000000")
        #Container.Label9_11.configure(highlightbackground="#d9d9d9")
        #Container.Label9_11.configure(highlightcolor="black")
        #Container.Label9_11.configure(text='''Swipe or Insert Debit/Credit card at anytime.''')

        Container.btnValue2 = tk.Button(Container)
        Container.btnValue2.place(relx=0.683, rely=0.035, height=67, width=67)
        Container.btnValue2.configure(activebackground="#ececec")
        Container.btnValue2.configure(activeforeground="#000000")
        Container.btnValue2.configure(background="#d9d9d9")
        Container.btnValue2.configure(disabledforeground="#a3a3a3")
        Container.btnValue2.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue2.configure(foreground="#000000")
        Container.btnValue2.configure(highlightbackground="#d9d9d9")
        Container.btnValue2.configure(highlightcolor="black")
        Container.btnValue2.configure(pady="0")
        Container.btnValue2.configure(text='''2''')

        Container.btnValue4 = tk.Button(Container)
        Container.btnValue4.place(relx=0.587, rely=0.158, height=67, width=67)
        Container.btnValue4.configure(activebackground="#ececec")
        Container.btnValue4.configure(activeforeground="#000000")
        Container.btnValue4.configure(background="#d9d9d9")
        Container.btnValue4.configure(disabledforeground="#a3a3a3")
        Container.btnValue4.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue4.configure(foreground="#000000")
        Container.btnValue4.configure(highlightbackground="#d9d9d9")
        Container.btnValue4.configure(highlightcolor="black")
        Container.btnValue4.configure(pady="0")
        Container.btnValue4.configure(text='''4''')

        Container.btnValue3 = tk.Button(Container)
        Container.btnValue3.place(relx=0.779, rely=0.035, height=67, width=67)
        Container.btnValue3.configure(activebackground="#ececec")
        Container.btnValue3.configure(activeforeground="#000000")
        Container.btnValue3.configure(background="#d9d9d9")
        Container.btnValue3.configure(disabledforeground="#a3a3a3")
        Container.btnValue3.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue3.configure(foreground="#000000")
        Container.btnValue3.configure(highlightbackground="#d9d9d9")
        Container.btnValue3.configure(highlightcolor="black")
        Container.btnValue3.configure(pady="0")
        Container.btnValue3.configure(text='''3''')

        Container.btnValue5 = tk.Button(Container)
        Container.btnValue5.place(relx=0.683, rely=0.158, height=67, width=67)
        Container.btnValue5.configure(activebackground="#ececec")
        Container.btnValue5.configure(activeforeground="#000000")
        Container.btnValue5.configure(background="#d9d9d9")
        Container.btnValue5.configure(disabledforeground="#a3a3a3")
        Container.btnValue5.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue5.configure(foreground="#000000")
        Container.btnValue5.configure(highlightbackground="#d9d9d9")
        Container.btnValue5.configure(highlightcolor="black")
        Container.btnValue5.configure(pady="0")
        Container.btnValue5.configure(text='''5''')

        Container.btnValue6 = tk.Button(Container)
        Container.btnValue6.place(relx=0.779, rely=0.158, height=67, width=67)
        Container.btnValue6.configure(activebackground="#ececec")
        Container.btnValue6.configure(activeforeground="#000000")
        Container.btnValue6.configure(background="#d9d9d9")
        Container.btnValue6.configure(disabledforeground="#a3a3a3")
        Container.btnValue6.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue6.configure(foreground="#000000")
        Container.btnValue6.configure(highlightbackground="#d9d9d9")
        Container.btnValue6.configure(highlightcolor="black")
        Container.btnValue6.configure(pady="0")
        Container.btnValue6.configure(text='''6''')

        Container.btnValue7 = tk.Button(Container)
        Container.btnValue7.place(relx=0.587, rely=0.281, height=67, width=67)
        Container.btnValue7.configure(activebackground="#ececec")
        Container.btnValue7.configure(activeforeground="#000000")
        Container.btnValue7.configure(background="#d9d9d9")
        Container.btnValue7.configure(disabledforeground="#a3a3a3")
        Container.btnValue7.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue7.configure(foreground="#000000")
        Container.btnValue7.configure(highlightbackground="#d9d9d9")
        Container.btnValue7.configure(highlightcolor="black")
        Container.btnValue7.configure(pady="0")
        Container.btnValue7.configure(text='''7''')

        Container.btnValue8 = tk.Button(Container)
        Container.btnValue8.place(relx=0.683, rely=0.281, height=67, width=67)
        Container.btnValue8.configure(activebackground="#ececec")
        Container.btnValue8.configure(activeforeground="#000000")
        Container.btnValue8.configure(background="#d9d9d9")
        Container.btnValue8.configure(disabledforeground="#a3a3a3")
        Container.btnValue8.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue8.configure(foreground="#000000")
        Container.btnValue8.configure(highlightbackground="#d9d9d9")
        Container.btnValue8.configure(highlightcolor="black")
        Container.btnValue8.configure(pady="0")
        Container.btnValue8.configure(text='''8''')

        Container.btnValue9 = tk.Button(Container)
        Container.btnValue9.place(relx=0.779, rely=0.281, height=67, width=67)
        Container.btnValue9.configure(activebackground="#ececec")
        Container.btnValue9.configure(activeforeground="#000000")
        Container.btnValue9.configure(background="#d9d9d9")
        Container.btnValue9.configure(disabledforeground="#a3a3a3")
        Container.btnValue9.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue9.configure(foreground="#000000")
        Container.btnValue9.configure(highlightbackground="#d9d9d9")
        Container.btnValue9.configure(highlightcolor="black")
        Container.btnValue9.configure(pady="0")
        Container.btnValue9.configure(text='''9''')

        Container.btnValueDecimal = tk.Button(Container)
        Container.btnValueDecimal.place(relx=0.587, rely=0.404, height=67, width=67)
        Container.btnValueDecimal.configure(activebackground="#ececec")
        Container.btnValueDecimal.configure(activeforeground="#000000")
        Container.btnValueDecimal.configure(background="#d9d9d9")
        Container.btnValueDecimal.configure(disabledforeground="#a3a3a3")
        Container.btnValueDecimal.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValueDecimal.configure(foreground="#000000")
        Container.btnValueDecimal.configure(highlightbackground="#d9d9d9")
        Container.btnValueDecimal.configure(highlightcolor="black")
        Container.btnValueDecimal.configure(pady="0")
        Container.btnValueDecimal.configure(text='''.''')

        Container.btnValue0 = tk.Button(Container)
        Container.btnValue0.place(relx=0.683, rely=0.404, height=67, width=67)
        Container.btnValue0.configure(activebackground="#ececec")
        Container.btnValue0.configure(activeforeground="#000000")
        Container.btnValue0.configure(background="#d9d9d9")
        Container.btnValue0.configure(disabledforeground="#a3a3a3")
        Container.btnValue0.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue0.configure(foreground="#000000")
        Container.btnValue0.configure(highlightbackground="#d9d9d9")
        Container.btnValue0.configure(highlightcolor="black")
        Container.btnValue0.configure(pady="0")
        Container.btnValue0.configure(text='''0''')

        Container.btnValue00 = tk.Button(Container)
        Container.btnValue00.place(relx=0.779, rely=0.404, height=67, width=67)
        Container.btnValue00.configure(activebackground="#ececec")
        Container.btnValue00.configure(activeforeground="#000000")
        Container.btnValue00.configure(background="#d9d9d9")
        Container.btnValue00.configure(disabledforeground="#a3a3a3")
        Container.btnValue00.configure(font="-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        Container.btnValue00.configure(foreground="#000000")
        Container.btnValue00.configure(highlightbackground="#d9d9d9")
        Container.btnValue00.configure(highlightcolor="black")
        Container.btnValue00.configure(pady="0")
        Container.btnValue00.configure(text='''00''')