#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Jul 06, 2020 11:21:42 PM EDT  platform: Windows NT

import sys
import Forms.formRegister_support
import Data.DB as posDB

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

codeRegister=None
 
class formRegister:
    def __init__(self, top=None):
        codeRegister=Forms.formRegister_support
        codeRegister.formRegister=self

        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        self.frameItems = tk.Frame(top)
        self.frameItems.place(relx=0.0, rely=0.061, relheight=0.857
                , relwidth=0.731)
        self.frameItems.configure(relief='sunken')
        self.frameItems.configure(borderwidth="2")
        self.frameItems.configure(relief="sunken")
        self.frameItems.configure(background="#d9d9d9")
        self.frameItems.configure(highlightbackground="#d9d9d9")
        self.frameItems.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.736, rely=0.015, height=21, width=44)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Patron:''')

        self.cboPatrons = ttk.Combobox(top)
        self.cboPatrons.place(relx=0.786, rely=0.0, relheight=0.047
                , relwidth=0.213)
        #self.cboPatrons.configure(textvariable=Forms.formRegister_support.combobox)
        self.cboPatrons.configure(takefocus="")

        self.frameOrderItems = tk.Frame(top)
        self.frameOrderItems.place(relx=0.736, rely=0.061, relheight=0.736
                , relwidth=0.277)
        self.frameOrderItems.configure(relief='sunken')
        self.frameOrderItems.configure(borderwidth="2")
        self.frameOrderItems.configure(relief="sunken")
        self.frameOrderItems.configure(background="#d9d9d9")
        self.frameOrderItems.configure(highlightbackground="#d9d9d9")
        self.frameOrderItems.configure(highlightcolor="black")

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.736, rely=0.804, height=21, width=59)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Sub Total:''')

        self.lblSubTotal = tk.Label(top)
        self.lblSubTotal.place(relx=0.917, rely=0.804, height=21, width=64)
        self.lblSubTotal.configure(activebackground="#f9f9f9")
        self.lblSubTotal.configure(activeforeground="black")
        self.lblSubTotal.configure(anchor='e')
        self.lblSubTotal.configure(background="#d9d9d9")
        self.lblSubTotal.configure(disabledforeground="#a3a3a3")
        self.lblSubTotal.configure(foreground="#000000")
        self.lblSubTotal.configure(highlightbackground="#d9d9d9")
        self.lblSubTotal.configure(highlightcolor="black")
        self.lblSubTotal.configure(justify='right')
        self.lblSubTotal.configure(text='''$000.00''')

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.736, rely=0.835, height=21, width=34)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Tax:''')

        self.Label7 = tk.Label(top)
        self.Label7.place(relx=0.736, rely=0.865, height=21, width=66)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Total:''')

        self.lblTax = tk.Label(top)
        self.lblTax.place(relx=0.917, rely=0.835, height=21, width=65)
        self.lblTax.configure(activebackground="#f9f9f9")
        self.lblTax.configure(activeforeground="black")
        self.lblTax.configure(anchor='e')
        self.lblTax.configure(background="#d9d9d9")
        self.lblTax.configure(disabledforeground="#a3a3a3")
        self.lblTax.configure(foreground="#000000")
        self.lblTax.configure(highlightbackground="#d9d9d9")
        self.lblTax.configure(highlightcolor="black")
        self.lblTax.configure(justify='right')
        self.lblTax.configure(text='''$000.00''')

        self.lblTotal = tk.Label(top)
        self.lblTotal.place(relx=0.877, rely=0.865, height=21, width=107)
        self.lblTotal.configure(activebackground="#f9f9f9")
        self.lblTotal.configure(activeforeground="black")
        self.lblTotal.configure(anchor='e')
        self.lblTotal.configure(background="#d9d9d9")
        self.lblTotal.configure(disabledforeground="#a3a3a3")
        self.lblTotal.configure(font="-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.lblTotal.configure(foreground="#000000")
        self.lblTotal.configure(highlightbackground="#d9d9d9")
        self.lblTotal.configure(highlightcolor="black")
        self.lblTotal.configure(text='''$000.00''')

        self.btnBack = tk.Button(top)
        self.btnBack.place(relx=0.0, rely=0.926, height=44, width=97)
        self.btnBack.configure(activebackground="#ff8040")
        self.btnBack.configure(activeforeground="#000000")
        self.btnBack.configure(background="#ff00ff")
        self.btnBack.configure(disabledforeground="#a3a3a3")
        self.btnBack.configure(font="-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnBack.configure(foreground="#000000")
        self.btnBack.configure(highlightbackground="#d9d9d9")
        self.btnBack.configure(highlightcolor="black")
        self.btnBack.configure(pady="0")
        self.btnBack.configure(state='disabled')
        self.btnBack.configure(text='''Back''')

        self.btnNext = tk.Button(top)
        self.btnNext.place(relx=0.101, rely=0.926, height=44, width=97)
        self.btnNext.configure(activebackground="#ff8040")
        self.btnNext.configure(activeforeground="#000000")
        self.btnNext.configure(background="#ff00ff")
        self.btnNext.configure(disabledforeground="#a3a3a3")
        self.btnNext.configure(font="-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnNext.configure(foreground="#000000")
        self.btnNext.configure(highlightbackground="#d9d9d9")
        self.btnNext.configure(highlightcolor="black")
        self.btnNext.configure(pady="0")
        self.btnNext.configure(state='disabled')
        self.btnNext.configure(text='''Next''')

        self.btnCredit = tk.Button(top)
        self.btnCredit.place(relx=0.897, rely=0.926, height=44, width=97)
        self.btnCredit.configure(activebackground="#ff8040")
        self.btnCredit.configure(activeforeground="#000000")
        self.btnCredit.configure(background="#00ffff")
        self.btnCredit.configure(disabledforeground="#a3a3a3")
        self.btnCredit.configure(font="-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnCredit.configure(foreground="#000000")
        self.btnCredit.configure(highlightbackground="#d9d9d9")
        self.btnCredit.configure(highlightcolor="black")
        self.btnCredit.configure(pady="0")
        self.btnCredit.configure(text='''Credit''')

        self.btnCash = tk.Button(top)
        self.btnCash.place(relx=0.796, rely=0.926, height=44, width=97)
        self.btnCash.configure(activebackground="#ff8040")
        self.btnCash.configure(activeforeground="#000000")
        self.btnCash.configure(background="#00ff00")
        self.btnCash.configure(disabledforeground="#a3a3a3")
        self.btnCash.configure(font="-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnCash.configure(foreground="#000000")
        self.btnCash.configure(highlightbackground="#d9d9d9")
        self.btnCash.configure(highlightcolor="black")
        self.btnCash.configure(pady="0")
        self.btnCash.configure(text='''Cash''')
        self.btnCash.configure(command=lambda: Forms.formRegister_support.ResizeFrameOrderItems(self))


        self.btnCancel = tk.Button(top)
        self.btnCancel.place(relx=0.635, rely=0.926, height=44, width=97)
        self.btnCancel.configure(activebackground="#ff8040")
        self.btnCancel.configure(activeforeground="#000000")
        self.btnCancel.configure(background="#ff80c0")
        self.btnCancel.configure(disabledforeground="#a3a3a3")
        self.btnCancel.configure(font="-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnCancel.configure(foreground="#000000")
        self.btnCancel.configure(highlightbackground="#d9d9d9")
        self.btnCancel.configure(highlightcolor="black")
        self.btnCancel.configure(pady="0")
        self.btnCancel.configure(text='''Cancel''')

        self.btnSave = tk.Button(top)
        self.btnSave.place(relx=0.534, rely=0.926, height=44, width=97)
        self.btnSave.configure(activebackground="#ff8040")
        self.btnSave.configure(activeforeground="#000000")
        self.btnSave.configure(background="#ffff80")
        self.btnSave.configure(disabledforeground="#a3a3a3")
        self.btnSave.configure(font="-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnSave.configure(foreground="#000000")
        self.btnSave.configure(highlightbackground="#d9d9d9")
        self.btnSave.configure(highlightcolor="black")
        self.btnSave.configure(pady="0")
        self.btnSave.configure(text='''Save''')

        self.Label2 = tk.Label(self.frameOrderItems)
        self.Label2.place(x=0, y=0, height=24, width=140)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(relief="raised")
        self.Label2.configure(text='''Item''')

        self.Label2_1 = tk.Label(self.frameOrderItems)
        self.Label2_1.place(x=140, y=0, height=24, width=40)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(relief="raised")
        self.Label2_1.configure(text='''Qty''')

        self.Label2_2 = tk.Label(self.frameOrderItems)
        self.Label2_2.place(x=180, y=0, height=24, width=60)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#d9d9d9")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(relief="raised")
        self.Label2_2.configure(text='''Unit Price''')

        self.canvasOrderItems=tk.Canvas(self.frameOrderItems)
        self.canvasOrderItems.place(x=0, y=25, width=240)

        self.frameOrderItems.bind("<Configure>", codeRegister.ResizeFrameOrderItems())


        default_style = {'activebackground': "#ff8040",'activeforeground': "#FF0000",'foreground': "#FF0000"}
        print("to do: stylize each food group button")
        #apply_conf(self.btnFoodItemGroup,default_style)

        rowCnt=-1
        intFoodItem=0
        curFoodItemGroups=posDB.GetFoodItemGroups()
        for rowTab in curFoodItemGroups:
            if(intFoodItem==0):
                intFoodItem=rowTab[0]

            rowCnt+=1
            arrayArgs=[]
            arrayVals=[]
            self.btnFoodItemGroup = tk.Button(top)
            self.btnFoodItemGroup.place(x=rowCnt*97, y=0, height=42, width=97)
            self.btnFoodItemGroup.configure(text=rowTab[1])
            self.btnFoodItemGroup.bind('<Button-1>', lambda event, arg=rowTab[0]: Forms.formRegister_support.LoadFoodItems(event, arg))
            #arrayArgAndVal=rowTab[2].split(",")
            
        #rowCnt=-1
        #intFoodItem=0
        #curFoodItems=posDB.GetFoodItemsByGroupRID(5)
        #for rowTab in curFoodItems:
        #    if(intFoodItem==0):
        #        intFoodItem=rowTab[0]

        #    rowCnt+=1
        #    arrayArgs=[]
        #    arrayVals=[]
        #    btn = tk.Button(self.frameItems)
        
        #    btn.place(x=rowCnt*97, y=0, height=42, width=97)
        #    btn.configure(text=rowTab[4])
        #    btn.bind('<Button-1>', lambda event, arg=rowTab[0]: Forms.formRegister_support.addtocart(event, arg))
        

        codeRegister.LoadFoodItems(event=None, arg=intFoodItem)
        codeRegister.LoadOrderItems()

    def apply_conf(self, control, conf):
        for k, v in conf.items():
            if hasattr(control, k):
               getattr(control, k).configure(**v)