#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Jul 03, 2020 11:04:44 AM EDT  platform: Windows NT
#    Jul 03, 2020 03:50:54 PM EDT  platform: Windows NT

import sys
import Forms.formRegister   

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

    formSubForm=None

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def ShowSubForm(ParentFrame, SubFormName):
    formSubForm=None
    formSubForm=Forms.formRegister.formRegister(top=ParentFrame)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    formTopLevel.vp_start_gui()





