#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Jul 06, 2020 11:21:46 PM EDT  platform: Windows NT

import sys
import threading
import Data.DB as posDB


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

formRegister=None

def UpdateGUI():
    formRegister.scrollOrderItems = tk.Scrollbar(formRegister.frameOrderItems)
    formRegister.scrollOrderItems.place(x=formRegister.frameOrderItems.winfo_width()-32, height=formRegister.frameOrderItems.winfo_height())
    formRegister.canvasOrderItems.config(yscrollcommand=formRegister.scrollOrderItems.set)
    formRegister.scrollOrderItems.config(command = formRegister.canvasOrderItems.yview )
    print("to do: fix scrollbar")
    #print(formRegister.canvasOrderItems.winfo_height())

def set_Tk_var():
    global combobox
    combobox = tk.StringVar()

def ResizeFrameOrderItems():
    ResizeTimer = threading.Timer(1, UpdateGUI)
    ResizeTimer.start()

def OrderItemClick(event, arg):
    print("to do: OrderItemClick")
    print(event)
    print(arg)

def LoadOrderItems():
    print("to do: LoadOrderItems")

    import locale
    locale.setlocale( locale.LC_ALL, '' )
    intLineHeight=40
    for line in range(15):
        formRegister.LineItemDesc=tk.Label(formRegister.canvasOrderItems)
        formRegister.LineItemDesc.place(x=0,y=line*intLineHeight)
        formRegister.LineItemDesc.config(text="label %d" % line, width=19,height=2,anchor="w")
        formRegister.LineItemDesc.config(font="-family {Segoe UI} -size 11")
        formRegister.LineItemDesc.bind('<Button-1>', lambda event, arg=line: OrderItemClick(event, arg))
        if (line % 2==1):
            formRegister.LineItemDesc.config(background="#c0c0c0")
            
        formRegister.LineItemDesc=tk.Label(formRegister.canvasOrderItems)
        formRegister.LineItemDesc.config(text="%d" % line, width=5,height=2)
        formRegister.LineItemDesc.place(x=140,y=line*intLineHeight)
        formRegister.LineItemDesc.config(font="-family {Segoe UI} -size 11")
        formRegister.LineItemDesc.bind('<Button-1>', lambda event, arg=line: OrderItemClick(event, arg))
        if (line % 2==1):
            formRegister.LineItemDesc.config(background="#c0c0c0")

        formRegister.LineItemDesc=tk.Label(formRegister.canvasOrderItems)
        formRegister.LineItemDesc.config(text=locale.currency( line, grouping=True ), width=7,height=2,anchor="e")
        formRegister.LineItemDesc.place(x=180,y=line*intLineHeight)
        formRegister.LineItemDesc.config(font="-family {Segoe UI} -size 11")
        formRegister.LineItemDesc.bind('<Button-1>', lambda event, arg=line: OrderItemClick(event, arg))
        if (line % 2==1):
            formRegister.LineItemDesc.config(background="#c0c0c0")
                
    intCanvasHeight=(line+1)*intLineHeight
    formRegister.canvasOrderItems.place(height=intCanvasHeight)
    formRegister.canvasOrderItems.config(scrollregion=(0,0,240,intCanvasHeight))



def LoadFoodItems(event, arg):
    print("to do: LoadFoodItems ", arg)
    #multiple pages
    #style buttons
    #different size buttons

    #print(formRegister.frameItems.children)
    #remove all existing buttons
    for child in formRegister.frameItems.winfo_children():
        child.destroy()
    
    #create buttons
    intRow=0
    intCol=-1
    curFoodItemGroups=posDB.GetFoodItemsByGroupRID(arg)
    for rowTab in curFoodItemGroups:
        if (intCol==6):
            if (intRow==10):
                #stop loading
                break

            intCol=0
            intRow+=1
        else:
            intCol+=1

        btn=tk.Button(formRegister.frameItems)
        
        btn.place(x=intCol*105, y=intRow*50+10, height=42, width=97)
        btn.configure(text=rowTab[4])
        btn.bind('<Button-1>', lambda event, arg=rowTab[0]: AddFoodItemToCart(event, arg))
        
def AddFoodItemToCart(event, arg):
    print("to do: AddFoodItemToCart ", arg)


def AddUPCItemToCart(event, arg):
    print("to do: AddUPCItemToCart ", arg)

