#############################################################################
# Generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#  Oct 06, 2020 04:12:23 PM EDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m55" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 732x570+576+168
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1916 1053
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab44 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Amount Due:} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {$000.00} 
    vTcl:DefineAlias "$top.lab45" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Amount Paid:} 
    vTcl:DefineAlias "$top.lab46" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {$000.00} 
    vTcl:DefineAlias "$top.lab47" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Amount Remaining:} 
    vTcl:DefineAlias "$top.lab48" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {$000.00} 
    vTcl:DefineAlias "$top.lab49" "Label6" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe50
    vTcl:DefineAlias "$top.tSe50" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe52
    vTcl:DefineAlias "$top.tSe52" "TSeparator3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m55
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    entry $top.ent56 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$top.ent56" "txtAmount" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Amount: 
    vTcl:DefineAlias "$top.lab57" "Label7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {$1} 
    vTcl:DefineAlias "$top.but58" "btnDollarBill1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Enter the payment amount and click "Add"} 
    vTcl:DefineAlias "$top.lab65" "Label9" vTcl:WidgetProc "Toplevel1" 1
    button $top.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 1 
    vTcl:DefineAlias "$top.but75" "btnValue1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab80 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Payments: 
    vTcl:DefineAlias "$top.lab80" "Label10" vTcl:WidgetProc "Toplevel1" 1
    button $top.but85 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {$5} 
    vTcl:DefineAlias "$top.but85" "btnDollarBill5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but86 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {$10} 
    vTcl:DefineAlias "$top.but86" "btnDollarBill10" vTcl:WidgetProc "Toplevel1" 1
    button $top.but87 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {$20} 
    vTcl:DefineAlias "$top.but87" "btnDollarBill20" vTcl:WidgetProc "Toplevel1" 1
    button $top.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Exact 
    vTcl:DefineAlias "$top.but88" "btnExactAmount" vTcl:WidgetProc "Toplevel1" 1
    button $top.but98 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Add 
    vTcl:DefineAlias "$top.but98" "btnAddPayment" vTcl:WidgetProc "Toplevel1" 1
    button $top.but111 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cancel -wraplength 60 
    vTcl:DefineAlias "$top.but111" "btnCancel" vTcl:WidgetProc "Toplevel1" 1
    button $top.but112 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Done 
    vTcl:DefineAlias "$top.but112" "btnDone" vTcl:WidgetProc "Toplevel1" 1
    button $top.but114 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Print 
    vTcl:DefineAlias "$top.but114" "btnPrint" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 2 
    vTcl:DefineAlias "$top.but53" "btnValue2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 4 
    vTcl:DefineAlias "$top.but54" "btnValue4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 3 
    vTcl:DefineAlias "$top.but55" "btnValue3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 5 
    vTcl:DefineAlias "$top.but56" "btnValue5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 6 
    vTcl:DefineAlias "$top.but57" "btnValue6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 7 
    vTcl:DefineAlias "$top.but59" "btnValue7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 8 
    vTcl:DefineAlias "$top.but60" "btnValue8" vTcl:WidgetProc "Toplevel1" 1
    button $top.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 9 
    vTcl:DefineAlias "$top.but61" "btnValue9" vTcl:WidgetProc "Toplevel1" 1
    button $top.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text . 
    vTcl:DefineAlias "$top.but62" "btnValueDecimal" vTcl:WidgetProc "Toplevel1" 1
    button $top.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 0 
    vTcl:DefineAlias "$top.but63" "btnValue0" vTcl:WidgetProc "Toplevel1" 1
    button $top.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {@Arial Unicode MS} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 00 
    vTcl:DefineAlias "$top.but64" "btnValue00" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledwindow::CreateCmd $top.scr65 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 100 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 150 
    vTcl:DefineAlias "$top.scr65" "Scrolledwindow1" vTcl:WidgetProc "Toplevel1" 1

    $top.scr65.01 configure -background white \
        -borderwidth 2 \
        -height 75 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -relief groove \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 125
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 0 -relx 0.096 -y 0 -rely 0.018 -width 0 -relwidth 0.173 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.273 -y 0 -rely 0.018 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.068 -y 0 -rely 0.07 -width 0 -relwidth 0.204 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.273 -y 0 -rely 0.07 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.123 -width 0 -relwidth 0.242 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.273 -y 0 -rely 0.123 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.tSe50 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.175 -width 0 -relwidth 0.505 \
        -height 0 -relheight 0.004 -anchor nw -bordermode inside 
    place $top.tSe52 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.474 -width 0 -relwidth 0.505 \
        -height 0 -relheight 0.004 -anchor nw -bordermode inside 
    place $top.ent56 \
        -in $top -x 0 -relx 0.273 -y 0 -rely 0.184 -width 74 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.164 -y 0 -rely 0.193 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.246 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.333 -width 0 -relwidth 0.505 \
        -height 0 -relheight 0.072 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.587 -y 0 -rely 0.035 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab80 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.719 -width 0 -relwidth 0.13 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.but85 \
        -in $top -x 0 -relx 0.082 -y 0 -rely 0.246 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but86 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.246 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but87 \
        -in $top -x 0 -relx 0.219 -y 0 -rely 0.246 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but88 \
        -in $top -x 0 -relx 0.301 -y 0 -rely 0.246 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but98 \
        -in $top -x 0 -relx 0.41 -y 0 -rely 0.246 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but111 \
        -in $top -x 0 -relx 0.874 -y 0 -rely 0.895 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but112 \
        -in $top -x 0 -relx 0.71 -y 0 -rely 0.895 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but114 \
        -in $top -x 0 -relx 0.546 -y 0 -rely 0.895 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.035 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.587 -y 0 -rely 0.158 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.779 -y 0 -rely 0.035 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.158 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.779 -y 0 -rely 0.158 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 0 -relx 0.587 -y 0 -rely 0.281 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.281 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.779 -y 0 -rely 0.281 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 0 -relx 0.587 -y 0 -rely 0.404 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.404 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.779 -y 0 -rely 0.404 -width 67 -relwidth 0 \
        -height 67 -relheight 0 -anchor nw -bordermode ignore 
    place $top.scr65 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.772 -width 0 -relwidth 0.511 \
        -height 0 -relheight 0.189 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

